server:
  port: 8080

spring:
  application:
    name: financial-tracker

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

logging:
  level:
    root: info

authorization:
  token:
    expiration-time-millis: ${TOKEN_EXPIRATION_TIME_MILLIS}
    signing-key-secret: ${TOKEN_SECRET}